name: nm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.13.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dataclasses=0.8=pyhc8e2a94_3
  - freetype=2.10.4=h5ab3b9f_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=1.15.0=py38_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu101
  - typing_extensions=3.10.0.0=pyhca03da5_0
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - astunparse==1.6.3
    - cachetools==4.2.2
    - charset-normalizer==2.0.5
    - clang==5.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.40.0
    - h5py==3.1.0
    - hydra-core==1.1.1
    - idna==3.2
    - imageio==2.9.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kornia==0.5.10
    - numpy==1.19.5
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opt-einsum==3.3.0
    - packaging==21.0
    - protobuf==3.18.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard-data-server==0.6.1
    - tensorboardx==2.4
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - tqdm==4.62.2
    - urllib3==1.26.6
    - wrapt==1.12.1
prefix: /home/henzler/.conda/envs/nm
